name: Deployment

on:
  push:
    branches:
      - master

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Build Docker Image
        run: docker build .

  start:
    name: Start Deployment
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Create Deployment
        id: create-deploy
        uses: actions/github-script@v2
        with:
          script: |
            const { data: {id} } = await github
              .repos
              .createDeployment({
                owner: context.repo.owner,
                repo: context.repo.repo,
                ref: context.ref,
                auto_merge: false,
                environment: 'test',
                required_contexts: [],
              });
            return id;
      
      - name: Get Deployment Info
        env:
          DEPLOYMENT_ID: ${{ steps.create-deploy.outputs.result }}
        run: |
          echo "$DEPLOYMENT_ID"
        
        
      