name: Deployment

on:
  pull_request:
    branches:
      - develop
      - master
  push:
    branches:
      - develop
      - master

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Build Docker Image
        run: docker build .
      
      - name: Create Deployment
        id: create-deploy
        uses: actions/github-script@v2
        with:
          script: |
            const deployment = await
              github.repos.createDeployment({
                owner: context.repo.owner,
                repo: context.repo.repo,
                ref: context.ref,
                environment: 'test',
                required_contexts: [],
              });
            console.log(deployment);
      
      - name: Get Deployment Info
        env:
          DEPLOYMENT_ID: ${{ steps.create-deploy.outputs.result.id }}
        run: |
          echo "${{steps.create-deploy.outputs.result}}"
          echo "Deployment: $DEPLOYMENT_ID"
        
        
      