name: Deployment

on:
  pull_request:
    branches:
      - develop
      - master
  push:
    branches:
      - develop
      - master

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Build Docker Image
        run: docker build .
      
      - name: Create Deployment
        id: create-deploy
        uses: actions/github-script@v2
        with:
          script: |
            const { data: {id} } = await github
              .repos
              .createDeployment({
                owner: context.repo.owner,
                repo: context.repo.repo,
                ref: context.ref,
                auto_merge: false,
                environment: 'test',
                required_contexts: [],
              });
            return id;
      
      - name: Get Deployment Info
        run: |
          echo "${{steps.create-deploy.outputs.result}}"
        
        
      